#!/bin/bash
./scc -cp scmc2c_multi_pass.sc
if [ "$CSCHEME_EXEC" == '' ]
then
	echo Warning: environment variable CSCHEME_EXEC unset! use ../cscheme instead
	if test -e "../cscheme"
	then
		CSCHEME_EXEC=../cscheme
	else
		echo Error: unable to find the cscheme inteprerter, abort!
		exit
	fi
fi

$CSCHEME_EXEC  csn.ss

gencompile(){
cat <<_EOF
cat fin-shell-g.ss | ./scompiler ../src/fin_shell.c
cat pre-passes-g.ss | ./scompiler ../src/pre_passes.c
(cd ../; make -j4)
_EOF
}

gencompile | bash

